### ISSUE TITLE
Kontaktaufnahme

### ISSUE THREAD

**Issue by amaanansari** [jhelgert/pyTranslines#1]
Hallo Jonathan,
@jhelgert 

gerne würde ich deinen Ilias Downloader (https://github.com/jhelgert/IliasDownloaderUniMA) weiterentwickeln. Dazu würde ich mich freuen, wenn ich dir ein paar Fragen stellen kann. Leider habe ich keine andere Möglichkeit gefunden, mit dir Kontakt aufzunehmen. Daher versuche ich's jetzt hier.

Du erreichst mich unter meiner Uni Mail: Vorname.Nachname@students.uni-mannheim.de

Ich freue mich, von dir zu hören :D

PS: Selbstverständlich kannst du das Issue hier dann löschen.

**Comment by jhelgert** [comment]
@AmaanAnsari Falls du immer noch Fragen hast (und meine Mail nicht angekommen sein sollte), kannst du mich auch unter vorname.nachname@posteo.de erreichen.
